apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: IBMVPCMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      additionalVolumes:
      - name: additional-volume-1
        profile: general-purpose
        sizeGiB: 50
      - name: additional-volume-2
        profile: custom
        sizeGiB: 50
        iops: 100
      bootVolume:
        sizeGiB: ${IBMVPC_WORKER_BOOT_VOLUME_SIZEGIB:=20}
