version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
    # Ignore controller-runtime as its upgraded manually.
    - dependency-name: "sigs.k8s.io/controller-runtime"
    # Ignore cluster-api as its upgraded manually.
    - dependency-name: "sigs.k8s.io/cluster-api/*"
    # Ignore k8s and its transitives modules as they are upgraded manually
    # together with controller-runtime.
    - dependency-name: "k8s.io/*"
    - dependency-name: "github.com/onsi/*"
    labels:
      - "ok-to-test"

  # Enable version updates for Go tools
  - package-ecosystem: "gomod"
    directory: "/hack/tools"
    schedule:
      interval: "weekly"
    ignore:
    # Ignore controller-runtime as its upgraded manually.
    - dependency-name: "sigs.k8s.io/controller-runtime/*"
    # Ignore cluster-api as its upgraded manually.
    - dependency-name: "sigs.k8s.io/cluster-api/*"
    - dependency-name: "sigs.k8s.io/controller-tools"
    # Ignore k8s and its transitives modules as they are upgraded manually
    # together with controller-runtime.
    - dependency-name: "k8s.io/*"
    - dependency-name: "github.com/onsi/*"
    labels:
      - "ok-to-test"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/hack/ccm"
    schedule:
      interval: "weekly"
