version: "2"
run:
  go: "1.25"
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - kubeapilinter # linter for Kube API conventions
  settings:
    custom:
      kubeapilinter:
        type: module
        description: KAL is the Kube-API-Linter and lints Kube like APIs based on API conventions and best practices.
        settings:
          linters:
            enable:
              - "nophase" # Phase fields are discouraged by the Kube API conventions, use conditions instead.

            # Linters below this line are disabled, pending conversation on how and when to enable them.
            disable:
            - "*" # We will manually enable new linters after understanding the impact. Disable all by default.
  exclusions:
    generated: strict
    paths:
      - zz_generated.*\.go$
      - ".*_test.go"  # Exclude test files.
    rules:
    ## KAL should only run on API folders.
    - path-except: "^api//*"
      linters:
        - kubeapilinter

    ## Excludes for old apiVersions that can be removed once the apiVersions are dropped (we don't want to make any changes to these APIs).
    - path: "api/powervs/v1beta2"
      linters:
        - kubeapilinter

    ## Excludes for VPC API's.
    - path: "api/vpc"
      linters:
        - kubeapilinter

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
