arch:
  - amd64
  - ppc64le
  - s390x
os:
  - linux

# Only clone the most recent commit.
git:
  depth: 1

language: go

go:
  - "1.13"

branches:
  only:
    - master

# Always set the project's Go import path to ensure that forked
# builds get cloned to the correct location.
go_import_path: sigs.k8s.io/cluster-api-provider-ibmcloud

before_install:
  - |
    export VERSION=latest
    export KUBEBUILDER_PATH=${GOPATH}/bin
    export KUBECTL_PATH=${GOPATH}/bin
  - make check
  - make test

# Skip the install process; let pre-commit.sh do it.
install: true

before_script:
  - docker login -u ${QUAY_USER} -p ${QUAY_KEY} ${QUAY_REPO}

script:
  - make images
  - make push-clusterctl-image
  - make push-controller-image

# TBD. Suppressing for now.
notifications:
email: false
