/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by MockGen. DO NOT EDIT.
// Source: ./powervs.go
//
// Generated by this command:
//
//	mockgen -source=./powervs.go -destination=./mock/powervs_generated.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/IBM-Cloud/power-go-client/power/models"
	gomock "go.uber.org/mock/gomock"
)

// MockPowerVS is a mock of PowerVS interface.
type MockPowerVS struct {
	ctrl     *gomock.Controller
	recorder *MockPowerVSMockRecorder
	isgomock struct{}
}

// MockPowerVSMockRecorder is the mock recorder for MockPowerVS.
type MockPowerVSMockRecorder struct {
	mock *MockPowerVS
}

// NewMockPowerVS creates a new mock instance.
func NewMockPowerVS(ctrl *gomock.Controller) *MockPowerVS {
	mock := &MockPowerVS{ctrl: ctrl}
	mock.recorder = &MockPowerVSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPowerVS) EXPECT() *MockPowerVSMockRecorder {
	return m.recorder
}

// CreateCosImage mocks base method.
func (m *MockPowerVS) CreateCosImage(ctx context.Context, body *models.CreateCosImageImportJob) (*models.JobReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCosImage", ctx, body)
	ret0, _ := ret[0].(*models.JobReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCosImage indicates an expected call of CreateCosImage.
func (mr *MockPowerVSMockRecorder) CreateCosImage(ctx, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCosImage", reflect.TypeOf((*MockPowerVS)(nil).CreateCosImage), ctx, body)
}

// CreateDHCPServer mocks base method.
func (m *MockPowerVS) CreateDHCPServer(ctx context.Context, body *models.DHCPServerCreate) (*models.DHCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDHCPServer", ctx, body)
	ret0, _ := ret[0].(*models.DHCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDHCPServer indicates an expected call of CreateDHCPServer.
func (mr *MockPowerVSMockRecorder) CreateDHCPServer(ctx, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDHCPServer", reflect.TypeOf((*MockPowerVS)(nil).CreateDHCPServer), ctx, body)
}

// CreateInstance mocks base method.
func (m *MockPowerVS) CreateInstance(ctx context.Context, body *models.PVMInstanceCreate) (*models.PVMInstanceList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstance", ctx, body)
	ret0, _ := ret[0].(*models.PVMInstanceList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstance indicates an expected call of CreateInstance.
func (mr *MockPowerVSMockRecorder) CreateInstance(ctx, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstance", reflect.TypeOf((*MockPowerVS)(nil).CreateInstance), ctx, body)
}

// DeleteDHCPServer mocks base method.
func (m *MockPowerVS) DeleteDHCPServer(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDHCPServer", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDHCPServer indicates an expected call of DeleteDHCPServer.
func (mr *MockPowerVSMockRecorder) DeleteDHCPServer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDHCPServer", reflect.TypeOf((*MockPowerVS)(nil).DeleteDHCPServer), ctx, id)
}

// DeleteImage mocks base method.
func (m *MockPowerVS) DeleteImage(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockPowerVSMockRecorder) DeleteImage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockPowerVS)(nil).DeleteImage), ctx, id)
}

// DeleteInstance mocks base method.
func (m *MockPowerVS) DeleteInstance(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInstance", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInstance indicates an expected call of DeleteInstance.
func (mr *MockPowerVSMockRecorder) DeleteInstance(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstance", reflect.TypeOf((*MockPowerVS)(nil).DeleteInstance), ctx, id)
}

// DeleteJob mocks base method.
func (m *MockPowerVS) DeleteJob(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJob", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteJob indicates an expected call of DeleteJob.
func (mr *MockPowerVSMockRecorder) DeleteJob(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJob", reflect.TypeOf((*MockPowerVS)(nil).DeleteJob), ctx, id)
}

// GetCosImages mocks base method.
func (m *MockPowerVS) GetCosImages(ctx context.Context, id string) (*models.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCosImages", ctx, id)
	ret0, _ := ret[0].(*models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCosImages indicates an expected call of GetCosImages.
func (mr *MockPowerVSMockRecorder) GetCosImages(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCosImages", reflect.TypeOf((*MockPowerVS)(nil).GetCosImages), ctx, id)
}

// GetDHCPServer mocks base method.
func (m *MockPowerVS) GetDHCPServer(ctx context.Context, id string) (*models.DHCPServerDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDHCPServer", ctx, id)
	ret0, _ := ret[0].(*models.DHCPServerDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDHCPServer indicates an expected call of GetDHCPServer.
func (mr *MockPowerVSMockRecorder) GetDHCPServer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDHCPServer", reflect.TypeOf((*MockPowerVS)(nil).GetDHCPServer), ctx, id)
}

// GetDatacenterDetails mocks base method.
func (m *MockPowerVS) GetDatacenterDetails(ctx context.Context, zone string) (*models.Datacenter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatacenterDetails", ctx, zone)
	ret0, _ := ret[0].(*models.Datacenter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatacenterDetails indicates an expected call of GetDatacenterDetails.
func (mr *MockPowerVSMockRecorder) GetDatacenterDetails(ctx, zone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatacenterDetails", reflect.TypeOf((*MockPowerVS)(nil).GetDatacenterDetails), ctx, zone)
}

// GetImage mocks base method.
func (m *MockPowerVS) GetImage(ctx context.Context, id string) (*models.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, id)
	ret0, _ := ret[0].(*models.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockPowerVSMockRecorder) GetImage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockPowerVS)(nil).GetImage), ctx, id)
}

// GetInstance mocks base method.
func (m *MockPowerVS) GetInstance(ctx context.Context, id string) (*models.PVMInstance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstance", ctx, id)
	ret0, _ := ret[0].(*models.PVMInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstance indicates an expected call of GetInstance.
func (mr *MockPowerVSMockRecorder) GetInstance(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstance", reflect.TypeOf((*MockPowerVS)(nil).GetInstance), ctx, id)
}

// GetJob mocks base method.
func (m *MockPowerVS) GetJob(ctx context.Context, id string) (*models.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", ctx, id)
	ret0, _ := ret[0].(*models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJob indicates an expected call of GetJob.
func (mr *MockPowerVSMockRecorder) GetJob(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockPowerVS)(nil).GetJob), ctx, id)
}

// GetNetworkByID mocks base method.
func (m *MockPowerVS) GetNetworkByID(ctx context.Context, id string) (*models.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkByID", ctx, id)
	ret0, _ := ret[0].(*models.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkByID indicates an expected call of GetNetworkByID.
func (mr *MockPowerVSMockRecorder) GetNetworkByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkByID", reflect.TypeOf((*MockPowerVS)(nil).GetNetworkByID), ctx, id)
}

// GetNetworkByName mocks base method.
func (m *MockPowerVS) GetNetworkByName(ctx context.Context, networkName string) (*models.NetworkReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkByName", ctx, networkName)
	ret0, _ := ret[0].(*models.NetworkReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkByName indicates an expected call of GetNetworkByName.
func (mr *MockPowerVSMockRecorder) GetNetworkByName(ctx, networkName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkByName", reflect.TypeOf((*MockPowerVS)(nil).GetNetworkByName), ctx, networkName)
}

// ListDHCPServers mocks base method.
func (m *MockPowerVS) ListDHCPServers(ctx context.Context) (models.DHCPServers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDHCPServers", ctx)
	ret0, _ := ret[0].(models.DHCPServers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDHCPServers indicates an expected call of ListDHCPServers.
func (mr *MockPowerVSMockRecorder) ListDHCPServers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDHCPServers", reflect.TypeOf((*MockPowerVS)(nil).ListDHCPServers), ctx)
}

// ListImages mocks base method.
func (m *MockPowerVS) ListImages(ctx context.Context) (*models.Images, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListImages", ctx)
	ret0, _ := ret[0].(*models.Images)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListImages indicates an expected call of ListImages.
func (mr *MockPowerVSMockRecorder) ListImages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImages", reflect.TypeOf((*MockPowerVS)(nil).ListImages), ctx)
}

// ListInstances mocks base method.
func (m *MockPowerVS) ListInstances(ctx context.Context) (*models.PVMInstances, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInstances", ctx)
	ret0, _ := ret[0].(*models.PVMInstances)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstances indicates an expected call of ListInstances.
func (mr *MockPowerVSMockRecorder) ListInstances(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstances", reflect.TypeOf((*MockPowerVS)(nil).ListInstances), ctx)
}

// ListNetworks mocks base method.
func (m *MockPowerVS) ListNetworks(ctx context.Context) (*models.Networks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNetworks", ctx)
	ret0, _ := ret[0].(*models.Networks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNetworks indicates an expected call of ListNetworks.
func (mr *MockPowerVSMockRecorder) ListNetworks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNetworks", reflect.TypeOf((*MockPowerVS)(nil).ListNetworks), ctx)
}
