apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: IBMVPCMachineTemplate
metadata:
  name: ibmvpcmachinetemplate-sample
spec:
  template:
    spec:
      image: r134-ea84bbec-7986-4ff5-8489-d9ec34611dd4
      profile: bx2-4x16
      sshKeys:
      - r134-2a82b725-e570-43d3-8b23-9539e8641944
      zone: us-south-1
