version: v2.5.0
name: golangci-lint-kube-api-linter
destination: ./bin
plugins:
- module: 'sigs.k8s.io/kube-api-linter'
  version: v0.0.0-20260206102632-39e3d06a2850 #To fetch the latest version: https://github.com/kubernetes-sigs/kube-api-linter?tab=readme-ov-file#golangci-lint-module
