apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibmcloud-service-account
  labels:
    app: clusterctl
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
