apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibmcloud-admin-role-binding
  labels:
    app: clusterctl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibmcloud-service-account
subjects:
  - kind: ServiceAccount
    name: ibmcloud-service-account
