# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 3000s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20221214-1b4dd4d69a'
    dir: 'hack/ccm'
    entrypoint: make
    env:
      - PULL_BASE_REF=${_PULL_BASE_REF}
      - HOME=/root
    args:
      - build-and-push-multi-arch
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '12345'
  _PULL_BASE_REF: 'dev'
