apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  cluster.x-k8s.io/v1beta1: v1beta1_v1beta2

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/infrastructure.cluster.x-k8s.io_ibmvpcclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_ibmvpcmachines.yaml
- bases/infrastructure.cluster.x-k8s.io_ibmvpcmachinetemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_ibmpowervsclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachines.yaml
- bases/infrastructure.cluster.x-k8s.io_ibmpowervsmachinetemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_ibmpowervsimages.yaml
- bases/infrastructure.cluster.x-k8s.io_ibmpowervsclustertemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_ibmvpcclustertemplates.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_ibmvpcclusters.yaml
- patches/webhook_in_ibmvpcmachines.yaml
- patches/webhook_in_ibmpowervsclusters.yaml
- patches/webhook_in_ibmpowervsmachines.yaml
- patches/webhook_in_ibmpowervsmachinetemplates.yaml
- patches/webhook_in_ibmvpcmachinetemplates.yaml
- patches/webhook_in_ibmpowervsimages.yaml
#- patches/webhook_in_ibmpowervsclustertemplates.yaml
#- patches/webhook_in_ibmvpcclustertemplates.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_ibmvpcclusters.yaml
- patches/cainjection_in_ibmvpcmachines.yaml
- patches/cainjection_in_ibmpowervsclusters.yaml
- patches/cainjection_in_ibmpowervsmachines.yaml
- patches/cainjection_in_ibmpowervsmachinetemplates.yaml
- patches/cainjection_in_ibmvpcmachinetemplates.yaml
- patches/cainjection_in_ibmpowervsimages.yaml
#- patches/cainjection_in_ibmpowervsclustertemplates.yaml
#- patches/cainjection_in_ibmvpcclustertemplates.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
