apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: "${CLUSTER_NAME}"
  name: "${CLUSTER_NAME}"
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - ${POD_CIDR:="192.168.0.0/16"}
    serviceDomain: ${SERVICE_DOMAIN:="cluster.local"}
    services:
      cidrBlocks:
        - ${SERVICE_CIDR:="10.128.0.0/12"}
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: IBMPowerVSCluster
    name: "${CLUSTER_NAME}"
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: "${CLUSTER_NAME}-control-plane"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: IBMPowerVSCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: "${CLUSTER_NAME}"
  name: "${CLUSTER_NAME}"
spec:
  serviceInstanceID: "${IBMPOWERVS_SERVICE_INSTANCE_ID}"
  network:
    name: "${IBMPOWERVS_NETWORK_NAME}"
  controlPlaneEndpoint:
    host: "${IBMPOWERVS_VIP_EXTERNAL}"
    port: ${API_SERVER_PORT:=6443}
