//go:build !ignore_autogenerated_core
// +build !ignore_autogenerated_core

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha3

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1beta1 "sigs.k8s.io/cluster-api-provider-ibmcloud/api/v1beta1"
	apiv1alpha3 "sigs.k8s.io/cluster-api/api/v1alpha3"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*IBMVPCCluster)(nil), (*v1beta1.IBMVPCCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCCluster_To_v1beta1_IBMVPCCluster(a.(*IBMVPCCluster), b.(*v1beta1.IBMVPCCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.IBMVPCCluster)(nil), (*IBMVPCCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IBMVPCCluster_To_v1alpha3_IBMVPCCluster(a.(*v1beta1.IBMVPCCluster), b.(*IBMVPCCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCClusterList)(nil), (*v1beta1.IBMVPCClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCClusterList_To_v1beta1_IBMVPCClusterList(a.(*IBMVPCClusterList), b.(*v1beta1.IBMVPCClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.IBMVPCClusterList)(nil), (*IBMVPCClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IBMVPCClusterList_To_v1alpha3_IBMVPCClusterList(a.(*v1beta1.IBMVPCClusterList), b.(*IBMVPCClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCClusterSpec)(nil), (*v1beta1.IBMVPCClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCClusterSpec_To_v1beta1_IBMVPCClusterSpec(a.(*IBMVPCClusterSpec), b.(*v1beta1.IBMVPCClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.IBMVPCClusterSpec)(nil), (*IBMVPCClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IBMVPCClusterSpec_To_v1alpha3_IBMVPCClusterSpec(a.(*v1beta1.IBMVPCClusterSpec), b.(*IBMVPCClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCClusterStatus)(nil), (*v1beta1.IBMVPCClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCClusterStatus_To_v1beta1_IBMVPCClusterStatus(a.(*IBMVPCClusterStatus), b.(*v1beta1.IBMVPCClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.IBMVPCClusterStatus)(nil), (*IBMVPCClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IBMVPCClusterStatus_To_v1alpha3_IBMVPCClusterStatus(a.(*v1beta1.IBMVPCClusterStatus), b.(*IBMVPCClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCMachine)(nil), (*v1beta1.IBMVPCMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCMachine_To_v1beta1_IBMVPCMachine(a.(*IBMVPCMachine), b.(*v1beta1.IBMVPCMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.IBMVPCMachine)(nil), (*IBMVPCMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IBMVPCMachine_To_v1alpha3_IBMVPCMachine(a.(*v1beta1.IBMVPCMachine), b.(*IBMVPCMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCMachineList)(nil), (*v1beta1.IBMVPCMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCMachineList_To_v1beta1_IBMVPCMachineList(a.(*IBMVPCMachineList), b.(*v1beta1.IBMVPCMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.IBMVPCMachineList)(nil), (*IBMVPCMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IBMVPCMachineList_To_v1alpha3_IBMVPCMachineList(a.(*v1beta1.IBMVPCMachineList), b.(*IBMVPCMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCMachineSpec)(nil), (*v1beta1.IBMVPCMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCMachineSpec_To_v1beta1_IBMVPCMachineSpec(a.(*IBMVPCMachineSpec), b.(*v1beta1.IBMVPCMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.IBMVPCMachineSpec)(nil), (*IBMVPCMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IBMVPCMachineSpec_To_v1alpha3_IBMVPCMachineSpec(a.(*v1beta1.IBMVPCMachineSpec), b.(*IBMVPCMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCMachineStatus)(nil), (*v1beta1.IBMVPCMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCMachineStatus_To_v1beta1_IBMVPCMachineStatus(a.(*IBMVPCMachineStatus), b.(*v1beta1.IBMVPCMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.IBMVPCMachineStatus)(nil), (*IBMVPCMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IBMVPCMachineStatus_To_v1alpha3_IBMVPCMachineStatus(a.(*v1beta1.IBMVPCMachineStatus), b.(*IBMVPCMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCMachineTemplate)(nil), (*v1beta1.IBMVPCMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCMachineTemplate_To_v1beta1_IBMVPCMachineTemplate(a.(*IBMVPCMachineTemplate), b.(*v1beta1.IBMVPCMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.IBMVPCMachineTemplate)(nil), (*IBMVPCMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IBMVPCMachineTemplate_To_v1alpha3_IBMVPCMachineTemplate(a.(*v1beta1.IBMVPCMachineTemplate), b.(*IBMVPCMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCMachineTemplateList)(nil), (*v1beta1.IBMVPCMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCMachineTemplateList_To_v1beta1_IBMVPCMachineTemplateList(a.(*IBMVPCMachineTemplateList), b.(*v1beta1.IBMVPCMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.IBMVPCMachineTemplateList)(nil), (*IBMVPCMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IBMVPCMachineTemplateList_To_v1alpha3_IBMVPCMachineTemplateList(a.(*v1beta1.IBMVPCMachineTemplateList), b.(*IBMVPCMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCMachineTemplateResource)(nil), (*v1beta1.IBMVPCMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCMachineTemplateResource_To_v1beta1_IBMVPCMachineTemplateResource(a.(*IBMVPCMachineTemplateResource), b.(*v1beta1.IBMVPCMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.IBMVPCMachineTemplateResource)(nil), (*IBMVPCMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IBMVPCMachineTemplateResource_To_v1alpha3_IBMVPCMachineTemplateResource(a.(*v1beta1.IBMVPCMachineTemplateResource), b.(*IBMVPCMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IBMVPCMachineTemplateSpec)(nil), (*v1beta1.IBMVPCMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_IBMVPCMachineTemplateSpec_To_v1beta1_IBMVPCMachineTemplateSpec(a.(*IBMVPCMachineTemplateSpec), b.(*v1beta1.IBMVPCMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.IBMVPCMachineTemplateSpec)(nil), (*IBMVPCMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_IBMVPCMachineTemplateSpec_To_v1alpha3_IBMVPCMachineTemplateSpec(a.(*v1beta1.IBMVPCMachineTemplateSpec), b.(*IBMVPCMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkInterface)(nil), (*v1beta1.NetworkInterface)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_NetworkInterface_To_v1beta1_NetworkInterface(a.(*NetworkInterface), b.(*v1beta1.NetworkInterface), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.NetworkInterface)(nil), (*NetworkInterface)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NetworkInterface_To_v1alpha3_NetworkInterface(a.(*v1beta1.NetworkInterface), b.(*NetworkInterface), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Subnet)(nil), (*v1beta1.Subnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_Subnet_To_v1beta1_Subnet(a.(*Subnet), b.(*v1beta1.Subnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Subnet)(nil), (*Subnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Subnet_To_v1alpha3_Subnet(a.(*v1beta1.Subnet), b.(*Subnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPC)(nil), (*v1beta1.VPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VPC_To_v1beta1_VPC(a.(*VPC), b.(*v1beta1.VPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.VPC)(nil), (*VPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VPC_To_v1alpha3_VPC(a.(*v1beta1.VPC), b.(*VPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VPCEndpoint)(nil), (*v1beta1.VPCEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_VPCEndpoint_To_v1beta1_VPCEndpoint(a.(*VPCEndpoint), b.(*v1beta1.VPCEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.VPCEndpoint)(nil), (*VPCEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_VPCEndpoint_To_v1alpha3_VPCEndpoint(a.(*v1beta1.VPCEndpoint), b.(*VPCEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*apiv1alpha3.APIEndpoint)(nil), (*apiv1beta1.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_APIEndpoint_To_v1beta1_APIEndpoint(a.(*apiv1alpha3.APIEndpoint), b.(*apiv1beta1.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*apiv1beta1.APIEndpoint)(nil), (*apiv1alpha3.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_APIEndpoint_To_v1alpha3_APIEndpoint(a.(*apiv1beta1.APIEndpoint), b.(*apiv1alpha3.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha3_IBMVPCCluster_To_v1beta1_IBMVPCCluster(in *IBMVPCCluster, out *v1beta1.IBMVPCCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_IBMVPCClusterSpec_To_v1beta1_IBMVPCClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_IBMVPCClusterStatus_To_v1beta1_IBMVPCClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_IBMVPCCluster_To_v1beta1_IBMVPCCluster is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCCluster_To_v1beta1_IBMVPCCluster(in *IBMVPCCluster, out *v1beta1.IBMVPCCluster, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCCluster_To_v1beta1_IBMVPCCluster(in, out, s)
}

func autoConvert_v1beta1_IBMVPCCluster_To_v1alpha3_IBMVPCCluster(in *v1beta1.IBMVPCCluster, out *IBMVPCCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_IBMVPCClusterSpec_To_v1alpha3_IBMVPCClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_IBMVPCClusterStatus_To_v1alpha3_IBMVPCClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_IBMVPCCluster_To_v1alpha3_IBMVPCCluster is an autogenerated conversion function.
func Convert_v1beta1_IBMVPCCluster_To_v1alpha3_IBMVPCCluster(in *v1beta1.IBMVPCCluster, out *IBMVPCCluster, s conversion.Scope) error {
	return autoConvert_v1beta1_IBMVPCCluster_To_v1alpha3_IBMVPCCluster(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCClusterList_To_v1beta1_IBMVPCClusterList(in *IBMVPCClusterList, out *v1beta1.IBMVPCClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta1.IBMVPCCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_IBMVPCCluster_To_v1beta1_IBMVPCCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_IBMVPCClusterList_To_v1beta1_IBMVPCClusterList is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCClusterList_To_v1beta1_IBMVPCClusterList(in *IBMVPCClusterList, out *v1beta1.IBMVPCClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCClusterList_To_v1beta1_IBMVPCClusterList(in, out, s)
}

func autoConvert_v1beta1_IBMVPCClusterList_To_v1alpha3_IBMVPCClusterList(in *v1beta1.IBMVPCClusterList, out *IBMVPCClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IBMVPCCluster, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_IBMVPCCluster_To_v1alpha3_IBMVPCCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_IBMVPCClusterList_To_v1alpha3_IBMVPCClusterList is an autogenerated conversion function.
func Convert_v1beta1_IBMVPCClusterList_To_v1alpha3_IBMVPCClusterList(in *v1beta1.IBMVPCClusterList, out *IBMVPCClusterList, s conversion.Scope) error {
	return autoConvert_v1beta1_IBMVPCClusterList_To_v1alpha3_IBMVPCClusterList(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCClusterSpec_To_v1beta1_IBMVPCClusterSpec(in *IBMVPCClusterSpec, out *v1beta1.IBMVPCClusterSpec, s conversion.Scope) error {
	out.Region = in.Region
	out.ResourceGroup = in.ResourceGroup
	out.VPC = in.VPC
	out.Zone = in.Zone
	if err := Convert_v1alpha3_APIEndpoint_To_v1beta1_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_IBMVPCClusterSpec_To_v1beta1_IBMVPCClusterSpec is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCClusterSpec_To_v1beta1_IBMVPCClusterSpec(in *IBMVPCClusterSpec, out *v1beta1.IBMVPCClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCClusterSpec_To_v1beta1_IBMVPCClusterSpec(in, out, s)
}

func autoConvert_v1beta1_IBMVPCClusterSpec_To_v1alpha3_IBMVPCClusterSpec(in *v1beta1.IBMVPCClusterSpec, out *IBMVPCClusterSpec, s conversion.Scope) error {
	out.Region = in.Region
	out.ResourceGroup = in.ResourceGroup
	out.VPC = in.VPC
	out.Zone = in.Zone
	if err := Convert_v1beta1_APIEndpoint_To_v1alpha3_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_IBMVPCClusterSpec_To_v1alpha3_IBMVPCClusterSpec is an autogenerated conversion function.
func Convert_v1beta1_IBMVPCClusterSpec_To_v1alpha3_IBMVPCClusterSpec(in *v1beta1.IBMVPCClusterSpec, out *IBMVPCClusterSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_IBMVPCClusterSpec_To_v1alpha3_IBMVPCClusterSpec(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCClusterStatus_To_v1beta1_IBMVPCClusterStatus(in *IBMVPCClusterStatus, out *v1beta1.IBMVPCClusterStatus, s conversion.Scope) error {
	if err := Convert_v1alpha3_VPC_To_v1beta1_VPC(&in.VPC, &out.VPC, s); err != nil {
		return err
	}
	out.Ready = in.Ready
	if err := Convert_v1alpha3_Subnet_To_v1beta1_Subnet(&in.Subnet, &out.Subnet, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_VPCEndpoint_To_v1beta1_VPCEndpoint(&in.VPCEndpoint, &out.VPCEndpoint, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_IBMVPCClusterStatus_To_v1beta1_IBMVPCClusterStatus is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCClusterStatus_To_v1beta1_IBMVPCClusterStatus(in *IBMVPCClusterStatus, out *v1beta1.IBMVPCClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCClusterStatus_To_v1beta1_IBMVPCClusterStatus(in, out, s)
}

func autoConvert_v1beta1_IBMVPCClusterStatus_To_v1alpha3_IBMVPCClusterStatus(in *v1beta1.IBMVPCClusterStatus, out *IBMVPCClusterStatus, s conversion.Scope) error {
	if err := Convert_v1beta1_VPC_To_v1alpha3_VPC(&in.VPC, &out.VPC, s); err != nil {
		return err
	}
	out.Ready = in.Ready
	if err := Convert_v1beta1_Subnet_To_v1alpha3_Subnet(&in.Subnet, &out.Subnet, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_VPCEndpoint_To_v1alpha3_VPCEndpoint(&in.VPCEndpoint, &out.VPCEndpoint, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_IBMVPCClusterStatus_To_v1alpha3_IBMVPCClusterStatus is an autogenerated conversion function.
func Convert_v1beta1_IBMVPCClusterStatus_To_v1alpha3_IBMVPCClusterStatus(in *v1beta1.IBMVPCClusterStatus, out *IBMVPCClusterStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_IBMVPCClusterStatus_To_v1alpha3_IBMVPCClusterStatus(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCMachine_To_v1beta1_IBMVPCMachine(in *IBMVPCMachine, out *v1beta1.IBMVPCMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_IBMVPCMachineSpec_To_v1beta1_IBMVPCMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_IBMVPCMachineStatus_To_v1beta1_IBMVPCMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_IBMVPCMachine_To_v1beta1_IBMVPCMachine is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCMachine_To_v1beta1_IBMVPCMachine(in *IBMVPCMachine, out *v1beta1.IBMVPCMachine, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCMachine_To_v1beta1_IBMVPCMachine(in, out, s)
}

func autoConvert_v1beta1_IBMVPCMachine_To_v1alpha3_IBMVPCMachine(in *v1beta1.IBMVPCMachine, out *IBMVPCMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_IBMVPCMachineSpec_To_v1alpha3_IBMVPCMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_IBMVPCMachineStatus_To_v1alpha3_IBMVPCMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_IBMVPCMachine_To_v1alpha3_IBMVPCMachine is an autogenerated conversion function.
func Convert_v1beta1_IBMVPCMachine_To_v1alpha3_IBMVPCMachine(in *v1beta1.IBMVPCMachine, out *IBMVPCMachine, s conversion.Scope) error {
	return autoConvert_v1beta1_IBMVPCMachine_To_v1alpha3_IBMVPCMachine(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCMachineList_To_v1beta1_IBMVPCMachineList(in *IBMVPCMachineList, out *v1beta1.IBMVPCMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.IBMVPCMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_IBMVPCMachineList_To_v1beta1_IBMVPCMachineList is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCMachineList_To_v1beta1_IBMVPCMachineList(in *IBMVPCMachineList, out *v1beta1.IBMVPCMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCMachineList_To_v1beta1_IBMVPCMachineList(in, out, s)
}

func autoConvert_v1beta1_IBMVPCMachineList_To_v1alpha3_IBMVPCMachineList(in *v1beta1.IBMVPCMachineList, out *IBMVPCMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]IBMVPCMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_IBMVPCMachineList_To_v1alpha3_IBMVPCMachineList is an autogenerated conversion function.
func Convert_v1beta1_IBMVPCMachineList_To_v1alpha3_IBMVPCMachineList(in *v1beta1.IBMVPCMachineList, out *IBMVPCMachineList, s conversion.Scope) error {
	return autoConvert_v1beta1_IBMVPCMachineList_To_v1alpha3_IBMVPCMachineList(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCMachineSpec_To_v1beta1_IBMVPCMachineSpec(in *IBMVPCMachineSpec, out *v1beta1.IBMVPCMachineSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Image = in.Image
	out.Zone = in.Zone
	out.Profile = in.Profile
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	if err := Convert_v1alpha3_NetworkInterface_To_v1beta1_NetworkInterface(&in.PrimaryNetworkInterface, &out.PrimaryNetworkInterface, s); err != nil {
		return err
	}
	out.SSHKeys = *(*[]*string)(unsafe.Pointer(&in.SSHKeys))
	return nil
}

// Convert_v1alpha3_IBMVPCMachineSpec_To_v1beta1_IBMVPCMachineSpec is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCMachineSpec_To_v1beta1_IBMVPCMachineSpec(in *IBMVPCMachineSpec, out *v1beta1.IBMVPCMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCMachineSpec_To_v1beta1_IBMVPCMachineSpec(in, out, s)
}

func autoConvert_v1beta1_IBMVPCMachineSpec_To_v1alpha3_IBMVPCMachineSpec(in *v1beta1.IBMVPCMachineSpec, out *IBMVPCMachineSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Image = in.Image
	out.Zone = in.Zone
	out.Profile = in.Profile
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	if err := Convert_v1beta1_NetworkInterface_To_v1alpha3_NetworkInterface(&in.PrimaryNetworkInterface, &out.PrimaryNetworkInterface, s); err != nil {
		return err
	}
	out.SSHKeys = *(*[]*string)(unsafe.Pointer(&in.SSHKeys))
	return nil
}

// Convert_v1beta1_IBMVPCMachineSpec_To_v1alpha3_IBMVPCMachineSpec is an autogenerated conversion function.
func Convert_v1beta1_IBMVPCMachineSpec_To_v1alpha3_IBMVPCMachineSpec(in *v1beta1.IBMVPCMachineSpec, out *IBMVPCMachineSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_IBMVPCMachineSpec_To_v1alpha3_IBMVPCMachineSpec(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCMachineStatus_To_v1beta1_IBMVPCMachineStatus(in *IBMVPCMachineStatus, out *v1beta1.IBMVPCMachineStatus, s conversion.Scope) error {
	out.InstanceID = in.InstanceID
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.InstanceStatus = in.InstanceStatus
	return nil
}

// Convert_v1alpha3_IBMVPCMachineStatus_To_v1beta1_IBMVPCMachineStatus is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCMachineStatus_To_v1beta1_IBMVPCMachineStatus(in *IBMVPCMachineStatus, out *v1beta1.IBMVPCMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCMachineStatus_To_v1beta1_IBMVPCMachineStatus(in, out, s)
}

func autoConvert_v1beta1_IBMVPCMachineStatus_To_v1alpha3_IBMVPCMachineStatus(in *v1beta1.IBMVPCMachineStatus, out *IBMVPCMachineStatus, s conversion.Scope) error {
	out.InstanceID = in.InstanceID
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.InstanceStatus = in.InstanceStatus
	return nil
}

// Convert_v1beta1_IBMVPCMachineStatus_To_v1alpha3_IBMVPCMachineStatus is an autogenerated conversion function.
func Convert_v1beta1_IBMVPCMachineStatus_To_v1alpha3_IBMVPCMachineStatus(in *v1beta1.IBMVPCMachineStatus, out *IBMVPCMachineStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_IBMVPCMachineStatus_To_v1alpha3_IBMVPCMachineStatus(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCMachineTemplate_To_v1beta1_IBMVPCMachineTemplate(in *IBMVPCMachineTemplate, out *v1beta1.IBMVPCMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_IBMVPCMachineTemplateSpec_To_v1beta1_IBMVPCMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_IBMVPCMachineTemplate_To_v1beta1_IBMVPCMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCMachineTemplate_To_v1beta1_IBMVPCMachineTemplate(in *IBMVPCMachineTemplate, out *v1beta1.IBMVPCMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCMachineTemplate_To_v1beta1_IBMVPCMachineTemplate(in, out, s)
}

func autoConvert_v1beta1_IBMVPCMachineTemplate_To_v1alpha3_IBMVPCMachineTemplate(in *v1beta1.IBMVPCMachineTemplate, out *IBMVPCMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_IBMVPCMachineTemplateSpec_To_v1alpha3_IBMVPCMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_IBMVPCMachineTemplate_To_v1alpha3_IBMVPCMachineTemplate is an autogenerated conversion function.
func Convert_v1beta1_IBMVPCMachineTemplate_To_v1alpha3_IBMVPCMachineTemplate(in *v1beta1.IBMVPCMachineTemplate, out *IBMVPCMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1beta1_IBMVPCMachineTemplate_To_v1alpha3_IBMVPCMachineTemplate(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCMachineTemplateList_To_v1beta1_IBMVPCMachineTemplateList(in *IBMVPCMachineTemplateList, out *v1beta1.IBMVPCMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.IBMVPCMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_IBMVPCMachineTemplateList_To_v1beta1_IBMVPCMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCMachineTemplateList_To_v1beta1_IBMVPCMachineTemplateList(in *IBMVPCMachineTemplateList, out *v1beta1.IBMVPCMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCMachineTemplateList_To_v1beta1_IBMVPCMachineTemplateList(in, out, s)
}

func autoConvert_v1beta1_IBMVPCMachineTemplateList_To_v1alpha3_IBMVPCMachineTemplateList(in *v1beta1.IBMVPCMachineTemplateList, out *IBMVPCMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]IBMVPCMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_IBMVPCMachineTemplateList_To_v1alpha3_IBMVPCMachineTemplateList is an autogenerated conversion function.
func Convert_v1beta1_IBMVPCMachineTemplateList_To_v1alpha3_IBMVPCMachineTemplateList(in *v1beta1.IBMVPCMachineTemplateList, out *IBMVPCMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta1_IBMVPCMachineTemplateList_To_v1alpha3_IBMVPCMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCMachineTemplateResource_To_v1beta1_IBMVPCMachineTemplateResource(in *IBMVPCMachineTemplateResource, out *v1beta1.IBMVPCMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha3_IBMVPCMachineSpec_To_v1beta1_IBMVPCMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_IBMVPCMachineTemplateResource_To_v1beta1_IBMVPCMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCMachineTemplateResource_To_v1beta1_IBMVPCMachineTemplateResource(in *IBMVPCMachineTemplateResource, out *v1beta1.IBMVPCMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCMachineTemplateResource_To_v1beta1_IBMVPCMachineTemplateResource(in, out, s)
}

func autoConvert_v1beta1_IBMVPCMachineTemplateResource_To_v1alpha3_IBMVPCMachineTemplateResource(in *v1beta1.IBMVPCMachineTemplateResource, out *IBMVPCMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta1_IBMVPCMachineSpec_To_v1alpha3_IBMVPCMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_IBMVPCMachineTemplateResource_To_v1alpha3_IBMVPCMachineTemplateResource is an autogenerated conversion function.
func Convert_v1beta1_IBMVPCMachineTemplateResource_To_v1alpha3_IBMVPCMachineTemplateResource(in *v1beta1.IBMVPCMachineTemplateResource, out *IBMVPCMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta1_IBMVPCMachineTemplateResource_To_v1alpha3_IBMVPCMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha3_IBMVPCMachineTemplateSpec_To_v1beta1_IBMVPCMachineTemplateSpec(in *IBMVPCMachineTemplateSpec, out *v1beta1.IBMVPCMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha3_IBMVPCMachineTemplateResource_To_v1beta1_IBMVPCMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_IBMVPCMachineTemplateSpec_To_v1beta1_IBMVPCMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha3_IBMVPCMachineTemplateSpec_To_v1beta1_IBMVPCMachineTemplateSpec(in *IBMVPCMachineTemplateSpec, out *v1beta1.IBMVPCMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_IBMVPCMachineTemplateSpec_To_v1beta1_IBMVPCMachineTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_IBMVPCMachineTemplateSpec_To_v1alpha3_IBMVPCMachineTemplateSpec(in *v1beta1.IBMVPCMachineTemplateSpec, out *IBMVPCMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_IBMVPCMachineTemplateResource_To_v1alpha3_IBMVPCMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_IBMVPCMachineTemplateSpec_To_v1alpha3_IBMVPCMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_IBMVPCMachineTemplateSpec_To_v1alpha3_IBMVPCMachineTemplateSpec(in *v1beta1.IBMVPCMachineTemplateSpec, out *IBMVPCMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_IBMVPCMachineTemplateSpec_To_v1alpha3_IBMVPCMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha3_NetworkInterface_To_v1beta1_NetworkInterface(in *NetworkInterface, out *v1beta1.NetworkInterface, s conversion.Scope) error {
	out.Subnet = in.Subnet
	return nil
}

// Convert_v1alpha3_NetworkInterface_To_v1beta1_NetworkInterface is an autogenerated conversion function.
func Convert_v1alpha3_NetworkInterface_To_v1beta1_NetworkInterface(in *NetworkInterface, out *v1beta1.NetworkInterface, s conversion.Scope) error {
	return autoConvert_v1alpha3_NetworkInterface_To_v1beta1_NetworkInterface(in, out, s)
}

func autoConvert_v1beta1_NetworkInterface_To_v1alpha3_NetworkInterface(in *v1beta1.NetworkInterface, out *NetworkInterface, s conversion.Scope) error {
	out.Subnet = in.Subnet
	return nil
}

// Convert_v1beta1_NetworkInterface_To_v1alpha3_NetworkInterface is an autogenerated conversion function.
func Convert_v1beta1_NetworkInterface_To_v1alpha3_NetworkInterface(in *v1beta1.NetworkInterface, out *NetworkInterface, s conversion.Scope) error {
	return autoConvert_v1beta1_NetworkInterface_To_v1alpha3_NetworkInterface(in, out, s)
}

func autoConvert_v1alpha3_Subnet_To_v1beta1_Subnet(in *Subnet, out *v1beta1.Subnet, s conversion.Scope) error {
	out.Ipv4CidrBlock = (*string)(unsafe.Pointer(in.Ipv4CidrBlock))
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.Zone = (*string)(unsafe.Pointer(in.Zone))
	return nil
}

// Convert_v1alpha3_Subnet_To_v1beta1_Subnet is an autogenerated conversion function.
func Convert_v1alpha3_Subnet_To_v1beta1_Subnet(in *Subnet, out *v1beta1.Subnet, s conversion.Scope) error {
	return autoConvert_v1alpha3_Subnet_To_v1beta1_Subnet(in, out, s)
}

func autoConvert_v1beta1_Subnet_To_v1alpha3_Subnet(in *v1beta1.Subnet, out *Subnet, s conversion.Scope) error {
	out.Ipv4CidrBlock = (*string)(unsafe.Pointer(in.Ipv4CidrBlock))
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.Zone = (*string)(unsafe.Pointer(in.Zone))
	return nil
}

// Convert_v1beta1_Subnet_To_v1alpha3_Subnet is an autogenerated conversion function.
func Convert_v1beta1_Subnet_To_v1alpha3_Subnet(in *v1beta1.Subnet, out *Subnet, s conversion.Scope) error {
	return autoConvert_v1beta1_Subnet_To_v1alpha3_Subnet(in, out, s)
}

func autoConvert_v1alpha3_VPC_To_v1beta1_VPC(in *VPC, out *v1beta1.VPC, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	return nil
}

// Convert_v1alpha3_VPC_To_v1beta1_VPC is an autogenerated conversion function.
func Convert_v1alpha3_VPC_To_v1beta1_VPC(in *VPC, out *v1beta1.VPC, s conversion.Scope) error {
	return autoConvert_v1alpha3_VPC_To_v1beta1_VPC(in, out, s)
}

func autoConvert_v1beta1_VPC_To_v1alpha3_VPC(in *v1beta1.VPC, out *VPC, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	return nil
}

// Convert_v1beta1_VPC_To_v1alpha3_VPC is an autogenerated conversion function.
func Convert_v1beta1_VPC_To_v1alpha3_VPC(in *v1beta1.VPC, out *VPC, s conversion.Scope) error {
	return autoConvert_v1beta1_VPC_To_v1alpha3_VPC(in, out, s)
}

func autoConvert_v1alpha3_VPCEndpoint_To_v1beta1_VPCEndpoint(in *VPCEndpoint, out *v1beta1.VPCEndpoint, s conversion.Scope) error {
	out.Address = (*string)(unsafe.Pointer(in.Address))
	out.FIPID = (*string)(unsafe.Pointer(in.FIPID))
	return nil
}

// Convert_v1alpha3_VPCEndpoint_To_v1beta1_VPCEndpoint is an autogenerated conversion function.
func Convert_v1alpha3_VPCEndpoint_To_v1beta1_VPCEndpoint(in *VPCEndpoint, out *v1beta1.VPCEndpoint, s conversion.Scope) error {
	return autoConvert_v1alpha3_VPCEndpoint_To_v1beta1_VPCEndpoint(in, out, s)
}

func autoConvert_v1beta1_VPCEndpoint_To_v1alpha3_VPCEndpoint(in *v1beta1.VPCEndpoint, out *VPCEndpoint, s conversion.Scope) error {
	out.Address = (*string)(unsafe.Pointer(in.Address))
	out.FIPID = (*string)(unsafe.Pointer(in.FIPID))
	return nil
}

// Convert_v1beta1_VPCEndpoint_To_v1alpha3_VPCEndpoint is an autogenerated conversion function.
func Convert_v1beta1_VPCEndpoint_To_v1alpha3_VPCEndpoint(in *v1beta1.VPCEndpoint, out *VPCEndpoint, s conversion.Scope) error {
	return autoConvert_v1beta1_VPCEndpoint_To_v1alpha3_VPCEndpoint(in, out, s)
}
