kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          provider-id: ibmpowervs://${CLUSTER_NAME}/'{{ v1.local_hostname }}'
        name: '{{ v1.local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          provider-id: ibmpowervs://${CLUSTER_NAME}/'{{ v1.local_hostname }}'

