name: Lint
on: [push, pull_request]
jobs:
  yamllint:
    name: Run yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # tag=v4.1.7
        with:
          ref: ${{ matrix.branch }}
      - name: Calculate go version
        id: vars
        run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # tag=v5.0.2
        with:
          go-version: ${{ steps.vars.outputs.go_version }}
      - name: Install yamllint
        run: make install-yamllint
      - name: Run yamllint
        run: make lint-yaml
      - name: Format Yaml files
        run: make format-yaml-files
