name: YamlLint
on: [push, pull_request]
jobs:
  yamllint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Run yamllint make target
        run: make yamllint
