name: Weekly security scan

on:
  schedule:
    # Cron for every Monday at 2:00 UTC.
    - cron: "0 2 * * 1"

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  scan:
    strategy:
      fail-fast: false
      matrix:
        branch: [ main, release-0.10, release-0.9 ]
    name: Trivy
    runs-on: ubuntu-24.04
    steps:
    - name: Check out code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # tag=v4.1.7
      with:
        ref: ${{ matrix.branch }}
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # tag=v5.0.2
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Run verify security target
      run: make verify-security
      # Send email notification
    - name: Send Email Notification (Success)
      if: success()
      uses: cinotify/github-action@main
      with:
        to: 'recipient@example.com'
        subject: "Security scan completed successfully"
        body: |
          The security scan for branch ${{ matrix.branch }} completed successfully.
          Please review the results if necessary.
        type: 'text/plain'
    - name: Send Email Notification (Failure)
      if: failure()
      uses: cinotify/github-action@main
      with:
        to: 'recipient@example.com'
        subject: "Security scan failed"
        body: |
          The security scan for branch ${{ matrix.branch }} has failed.
          Please review the results and take appropriate action.
        type: 'text/plain'
      # Send slack notification
    - name: Send Slack Notification (Success)
      if: success()
      uses: slackapi/slack-github-action@v1
      with:
        slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
        channel: '#channel'
        text: "Security scan completed successfully on branch ${{ matrix.branch }}."
    - name: Send Slack Notification (Failure)
      if: failure()
      uses: slackapi/slack-github-action@v1
      with:
        slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
        channel: '#channel'
        text: "Security scan failed on branch ${{ matrix.branch }}. Please review the results."
